//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.18 at 09:47:13 上午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://utils.uia/layout", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uia.utils.layout;
